### ISSUE TITLE
`rmarkdown::render_site()` producing errors

### ISSUE THREAD

**Issue by dcossyleon** [darwinanddavis/EmoRyCodingClub#1]
Hey @darwinanddavis, I've pulled the most recent changes, but I'm getting some errors when I try to render the site with `rmarkdown::render_site()`. When I knit the .Rmd pages individually to try to work around this the formatting breaks.

![image](https://user-images.githubusercontent.com/29008894/60563134-8a890900-9d28-11e9-8c4d-fa8bdbab3f23.png)

I'm less familiar with using RMarkdown for non-HTML outputs, so I'm not sure if this sort of thing happens when specifying multiple output types for the `index.Rmd` and not the `_site.yml` file? 

I suppose this could be a local issue--but do you have any ideas on what I could try based on the error message I'm getting below?

```
Error: Functions that produce HTML output found in document targeting latex output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: yes

Note however that the HTML output will not be visible in non-HTML formats.

In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'packages'
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'packages'
Execution halted

Exited with status 1.
```

When I include `always_allow_html: yes` it doesn't seem to solve things for me :-/

**Comment by darwinanddavis** [comment]
@dcossyleon, it looks like a HTML rendering error because the raw HTML align text div is displayed next to the misaligned images. I've only been outputting HTML for all the master and index files and not using other non-HTML outputs like PDF. Try updating the yaml with the following:

always_allow_html: yes
self_contained: false
keep_md: true

Below is the full yaml with the new options in their respective positions.

*******************************************************************

---
title: "Welcome to the EmoRy Coding Club"
header-includes: \usepackage{float}
fontsize: 12
geometry: margin=1in
documentclass: article
linkcolor: blue
urlcolor: blue
citecolor: red
always_allow_html: yes
output:
  html_document:
    highlight: tango
    code_folding: show
    toc: yes
    toc_depth: 2
    number_sections: no
    toc_float: yes
    self_contained: false
    keep_md: true
  pdf_document:
    includes:
      in_header: # add .tex file with header content
    highlight: tango
    template: null
    toc: yes
    toc_depth: 3
    number_sections: false
    fig_width: 4
    fig_height: 5
    fig_caption: true
    df_print: tibble 
    citation_package: biblatex # natbib
    latex_engine: xelatex #pdflatex # lualatex
    keep_tex: true # keep .tex file in dir 
  word_document:
    highlight: tango
    keep_md: yes
    pandoc_args: --smart
    #reference: mystyles.docx
    toc: yes
inludes:
  before_body: before_body.tex
subtitle: 
tags:
- nothing
- nothingness
--- 

*******************************************************************

I also uncommented the klippy code chunk from your original Rmd files because I got an error and I don't know what klippy is.

```{r klippy, echo=FALSE, include=TRUE}
# klippy::klippy()
```

If keeping this in solves your error, then feel free to revert back and let me know what else I need to run klippy so I can get it working on my end.

**Comment by dcossyleon** [comment]
I did finally get this to render properly. I think the image weirdness was happening because line breaks were excepted above and below the <div>  container that contained the images. 

[klippy](https://rlesur.github.io/klippy/articles/klippy.html) is a cool package that makes the code chunks copy and paste-able, but as we talked about last time, it's probably better to discourage copying and pasting for now anyway :)
